apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ .Values.sampleApp.meta.name }}
              servicePort: {{ .Values.sampleApp.service.port }}
            path: /*