apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sampleApp.meta.name }}
  namespace: {{ .Values.sampleApp.meta.namespace }}
spec:
  selector:
    app:  {{ .Values.sampleApp.meta.label }}
  ports:
    - port: {{ .Values.sampleApp.service.port }}
      targetPort: {{ .Values.sampleApp.service.targetport }}
  type: {{ .Values.sampleApp.service.type }}
